<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="US_Canada_1000_Products.xml.gz" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="US_Canada_1000_Products.xml.gz" />
    <EmbeddedResource Include="US_Canada_100_Stores.xml.gz" />
  </ItemGroup>

</Project>
